/* This file was generated by the Hex-Rays decompiler version 8.2.0.221215.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
// int puts(const char *s);
// size_t strlen(const char *s);
// int printf(const char *format, ...);
// void *memset(void *s, int c, size_t n);
// int strcmp(const char *s1, const char *s2);
// int fflush(FILE *stream);
// int atoi(const char *nptr);
// __int64 __isoc99_scanf(const char *, ...); weak
// void __noreturn exit(int status);
// int __fastcall _cxa_finalize(void *);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
char *deregister_tm_clones();
__int64 register_tm_clones();
char *_do_global_dtors_aux();
__int64 __fastcall frame_dummy(); // weak
int wt();
int nice();
int try();
int but();
int this();
int it();
int not();
int that();
int easy();
void __noreturn __syscall_malloc();
int ___syscall_malloc();
int __cdecl main(int argc, const char **argv, const char **envp);
void term_proc();
// int __fastcall _libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int __fastcall __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

void *_dso_handle = &_dso_handle; // idb
char _bss_start; // weak
// extern struct _IO_FILE *stdin;


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 40E8: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0LL);
}
// 1026: control flows out of bounds to 0

//----- (00000000000010D0) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (__fastcall *)(int, char **, char **))main, v4, &retaddr, 0LL, 0LL, a3, &v5);
  __halt();
}
// 10DA: positive sp value 8 has been found
// 10E1: variable 'v3' is possibly undefined

//----- (0000000000001100) ----------------------------------------------------
char *deregister_tm_clones()
{
  return &_bss_start;
}
// 4070: using guessed type char _bss_start;

//----- (0000000000001130) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}

//----- (0000000000001170) ----------------------------------------------------
char *_do_global_dtors_aux()
{
  char *result; // rax

  if ( !_bss_start )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    _bss_start = 1;
  }
  return result;
}
// 4070: using guessed type char _bss_start;

//----- (00000000000011B0) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 11B0: using guessed type __int64 __fastcall frame_dummy();

//----- (00000000000011C0) ----------------------------------------------------
int wt()
{
  return puts("********");
}

//----- (00000000000011E0) ----------------------------------------------------
int nice()
{
  return puts("nice");
}

//----- (0000000000001200) ----------------------------------------------------
int try()
{
  return puts("try");
}

//----- (0000000000001220) ----------------------------------------------------
int but()
{
  return puts("but");
}

//----- (0000000000001240) ----------------------------------------------------
int this()
{
  return puts("this");
}

//----- (0000000000001260) ----------------------------------------------------
int it()
{
  return puts("it");
}

//----- (0000000000001280) ----------------------------------------------------
int not()
{
  return puts("not.");
}

//----- (00000000000012A0) ----------------------------------------------------
int that()
{
  return puts("that.");
}

//----- (00000000000012C0) ----------------------------------------------------
int easy()
{
  return puts("easy.");
}

//----- (00000000000012E0) ----------------------------------------------------
void __noreturn __syscall_malloc()
{
  puts("Nope.");
  exit(1);
}

//----- (0000000000001300) ----------------------------------------------------
int ___syscall_malloc()
{
  return puts("Good job.");
}

//----- (0000000000001320) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  char v3; // al
  size_t v5; // [rsp+10h] [rbp-50h]
  bool v6; // [rsp+1Bh] [rbp-45h]
  char nptr[4]; // [rsp+1Ch] [rbp-44h] BYREF
  char v8; // [rsp+20h] [rbp-40h] BYREF
  char v9[30]; // [rsp+21h] [rbp-3Fh]
  char s[9]; // [rsp+3Fh] [rbp-21h] BYREF
  size_t v11; // [rsp+48h] [rbp-18h]
  int v12; // [rsp+50h] [rbp-10h]
  int i; // [rsp+54h] [rbp-Ch]
  int v14; // [rsp+58h] [rbp-8h]
  int v15; // [rsp+5Ch] [rbp-4h]

  v15 = 0;
  printf("Please enter key: ");
  v14 = __isoc99_scanf("%23s", &v8);
  if ( v14 != 1 )
    __syscall_malloc();
  if ( v9[0] != 50 )
    __syscall_malloc();
  if ( v8 != 52 )
    __syscall_malloc();
  fflush(stdin);
  memset(s, 0, sizeof(s));
  s[0] = 42;
  nptr[3] = 0;
  v11 = 2LL;
  for ( i = 1; ; ++i )
  {
    v6 = 0;
    if ( strlen(s) < 8 )
    {
      v5 = v11;
      v6 = v5 < strlen(&v8);
    }
    if ( !v6 )
      break;
    nptr[0] = v9[v11 - 1];
    nptr[1] = v9[v11];
    nptr[2] = v9[v11 + 1];
    v3 = atoi(nptr);
    s[i] = v3;
    v11 += 3LL;
  }
  s[i] = 0;
  v12 = strcmp(s, "********");
  if ( v12 == -2 )
    __syscall_malloc();
  if ( v12 == -1 )
    __syscall_malloc();
  if ( v12 )
  {
    if ( v12 != 1 )
    {
      if ( v12 != 2 )
      {
        if ( v12 != 3 )
        {
          if ( v12 != 4 )
          {
            if ( v12 != 5 )
            {
              if ( v12 != 115 )
                __syscall_malloc();
              __syscall_malloc();
            }
            __syscall_malloc();
          }
          __syscall_malloc();
        }
        __syscall_malloc();
      }
      __syscall_malloc();
    }
    __syscall_malloc();
  }
  ___syscall_malloc();
  return 0;
}
// 10A0: using guessed type __int64 __isoc99_scanf(const char *, ...);
// 1320: using guessed type char s[9];

//----- (0000000000001580) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=42 queued=20 decompiled=20 lumina nreq=0 worse=0 better=0
// ALL OK, 20 function(s) have been successfully decompiled
