/* This file was generated by the Hex-Rays decompiler version 8.2.0.221215.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
void sub_1030();
// int strcmp(const char *s1, const char *s2);
// int __cdecl __libc_start_main(int (__cdecl *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int printf(const char *format, ...);
// int fflush(FILE *stream);
// int puts(const char *s);
// void exit(int status);
// size_t strlen(const char *s);
// void *memset(void *s, int c, size_t n);
// int __cdecl __isoc99_scanf(_DWORD, _DWORD); weak
// int atoi(const char *nptr);
int __cdecl sub_10E0(_DWORD); // weak
// void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>);
void sub_111C();
void _x86_get_pc_thunk_bx();
char *deregister_tm_clones();
int register_tm_clones();
char *_do_global_dtors_aux();
int frame_dummy();
void _x86_get_pc_thunk_dx();
void __noreturn no();
int xd();
int ok();
int __cdecl main(int argc, const char **argv, const char **envp);
int xxd();
int n();
int xxxd();
int ww();
int xyxxd();
void term_proc();
// int __cdecl _cxa_finalize(void *);

//-------------------------------------------------------------------------
// Data declarations

void *_dso_handle = &_dso_handle; // weak
char _bss_start; // weak
// extern struct _IO_FILE *stdin;
// extern _UNKNOWN _gmon_start__; weak


//----- (00001000) --------------------------------------------------------
void *init_proc()
{
  void *result; // eax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (void *)((int (*)(void))_gmon_start__)();
  return result;
}

//----- (00001030) --------------------------------------------------------
void sub_1030()
{
  __asm { jmp     dword ptr [ebx+8] }
}
// 1036: unbalanced stack, ignored a potential tail call

//----- (000010F0) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>)
{
  int v2; // esi
  int v3; // [esp-4h] [ebp-4h] BYREF
  char *retaddr; // [esp+0h] [ebp+0h] BYREF

  v2 = v3;
  v3 = a1;
  __libc_start_main((int (__cdecl *)(int, char **, char **))main, v2, &retaddr, 0, 0, a2, &v3);
  __halt();
}
// 10F7: positive sp value 4 has been found

//----- (0000111C) --------------------------------------------------------
void sub_111C()
{
  ;
}

//----- (00001120) --------------------------------------------------------
void _x86_get_pc_thunk_bx()
{
  ;
}

//----- (00001130) --------------------------------------------------------
char *deregister_tm_clones()
{
  return &_bss_start;
}
// 1130: could not find valid save-restore pair for ebp
// 703C: using guessed type char _bss_start;

//----- (00001170) --------------------------------------------------------
int register_tm_clones()
{
  return 0;
}
// 1170: could not find valid save-restore pair for ebp

//----- (000011C0) --------------------------------------------------------
char *_do_global_dtors_aux()
{
  char *result; // eax

  if ( !_bss_start )
  {
    if ( &_cxa_finalize )
      sub_10E0(_dso_handle);
    result = deregister_tm_clones();
    _bss_start = 1;
  }
  return result;
}
// 10E0: using guessed type int __cdecl sub_10E0(_DWORD);
// 7038: using guessed type void *_dso_handle;
// 703C: using guessed type char _bss_start;

//----- (00001210) --------------------------------------------------------
int frame_dummy()
{
  return register_tm_clones();
}

//----- (00001219) --------------------------------------------------------
void _x86_get_pc_thunk_dx()
{
  ;
}

//----- (00001220) --------------------------------------------------------
void __noreturn no()
{
  puts("Nope.");
  exit(1);
}

//----- (00001260) --------------------------------------------------------
int xd()
{
  puts(
    "Iii sapores crescit rei habetur disputo. An ab istud mo prius tanta error debet. Firma foret tes mea age capax sumne"
    ". Ex ex ipsas actum culpa neque ab saepe. Existenti et principia co immittere probandam imaginari re mo. Quapropter "
    "industriam ibi cui dissimilem cucurbitas progressus perciperem. Essendi ratione si habetur gi ignotas cognitu nusqua"
    "m et.Sumpta vel uti obvium hoc tribuo libere. Egisse ingens hic sed inquam tamque rum gaudet aetate dat. Sum ignem j"
    "am ullas tur nexum vul. Divelli certius si errandi accipio colores de numerum. Is quavis tangam istius lumini essent"
    " vereor ab si. Aliam rea res tango vix simul certa certi.Imponere tractatu advenire ad superest occurret se quicquam"
    " si ha. Nihil solus pappo mo ei. Tum iis rom innata gloria hos quales. Ac sequentium im sufficeret institutum ad per"
    "mittere at. Aliquis aliarum quaenam at de totaque notitia ob exhibet. Simus tes sae sacra error. Neque nomen ac ad o"
    "pera is reges gi nobis. Se in objectivae ab is offerendum videbuntur satyriscos. Uno sequor tritam mediam essent eae"
    " usu rea. \t\t\tActum situs ideam solum uti signa mem. De ignotas errores gi remotam invenio suppono. At argumentis "
    "facultatem attendenti explicatur transferre ob du reperiatur. Gi du mali quod fuit an unum ei. Mea sperare ego senti"
    "at idearum spatium quaedam. Prius cur locus utrum hodie porro mente ope. Accepit liberam externo qui fal. \t\t\tVolu"
    "nt illico eas animus ita odores sacras ima. De ipsa vi ad deus alio ut deum. Acquiri aliquot in liquida vi maximam i"
    "s timenda. Ad aliquandiu ei facillimam repugnaret scripturas. Mearum imo namque falsae notatu hic mea non. Ero commu"
    "nibus exponantur hae sui quo virtutibus aliquandiu. \t\t\tNeque fieri horum errem ab me eo credo. Hanc sic meo quae "
    "ipsa. Fal membrorum existenti conservet per sapientia dubitavit. Apta gi de et enim gnum data. Id quadratam ut archi"
    "mede attingere re ne. Humanam infusum has iis veteris mei occasio replere istarum. Emanant poterit capaces at in num"
    "erum de exigere ob chartam. Cui tollitur periculi cau veniebat. Communibus vi at ut permittere ex progressum pauperr"
    "imi conflantur. Mentibus eo patiatur dependet et reliquis tenebras. Peccant ejusdem apertum et dicetur mo at. Ingeni"
    "osi exponetur sequentia si se. Affirmarem respondere desiderant ac vi quantumvis praecipuus se ex. Ob externis tanga"
    "tur existens recenseo ac. Una summam ens essent optime tempus firmum realis eos. Cetera fallat sic numero mei inquam"
    " rom ope revera. Causis humana fal verius ausint ope. Odor has alia otii dare ausi nunc quo agi. Praefatio du compon"
    "ant albedinem ad perlegere. Externarum ne si archimedes negationem. Praeditis scriptura antiquius cupientem ea nonnu"
    "llae recurrunt ad. Simile ut ne egisse animos fingam de. Scirem in coelum possim altera co");
  return puts(
           "Author gi ex si im fallat istius. Refutent supposui qua sim nihilque. Me ob omni ideo gnum casu. Gi supersunt"
           " colligere inhaereat me sapientia is delaberer. Rom facillimam rem expectabam rum inchoandum mei. Apertum id "
           "suppono ac generis. Ab scio ad eo deus haud meae. Hominem ex vi ut remanet at quidnam. \t\t\tTunc ullo ut ann"
           "o poni voce de haud. Mallent prudens suo deumque qui sim invicem. Suum mo item inde de modi unde. Suo deo omn"
           "i quia opus. Co an habent inesse semper.Et innatas dominum cogitem sperare sopitum in. Substantia dei credidi"
           "sse vim iis excogitent exhibentur sub.");
}

//----- (000012A0) --------------------------------------------------------
int ok()
{
  return puts("Good job.");
}

//----- (000012D0) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  char v3; // al
  size_t v5; // [esp+10h] [ebp-48h]
  bool v6; // [esp+17h] [ebp-41h]
  char nptr[4]; // [esp+1Fh] [ebp-39h] BYREF
  char v8; // [esp+23h] [ebp-35h] BYREF
  char v9[23]; // [esp+24h] [ebp-34h]
  char s[9]; // [esp+3Bh] [ebp-1Dh] BYREF
  size_t v11; // [esp+44h] [ebp-14h]
  int i; // [esp+48h] [ebp-10h]
  int v13; // [esp+4Ch] [ebp-Ch]
  int v14; // [esp+50h] [ebp-8h]

  v14 = 0;
  printf("Please enter key: ");
  v13 = __isoc99_scanf("%23s", &v8);
  if ( v13 != 1 )
    no();
  if ( v9[0] != 48 )
    no();
  if ( v8 != 48 )
    no();
  fflush(stdin);
  memset(s, 0, sizeof(s));
  s[0] = 100;
  nptr[3] = 0;
  v11 = 2;
  for ( i = 1; ; ++i )
  {
    v6 = 0;
    if ( strlen(s) < 8 )
    {
      v5 = v11;
      v6 = v5 < strlen(&v8);
    }
    if ( !v6 )
      break;
    nptr[0] = v9[v11 - 1];
    nptr[1] = v9[v11];
    nptr[2] = v9[v11 + 1];
    v3 = atoi(nptr);
    s[i] = v3;
    v11 += 3;
  }
  s[i] = 0;
  if ( strcmp(s, "delabere") )
    no();
  ok();
  return 0;
}
// 10C0: using guessed type int __cdecl __isoc99_scanf(_DWORD, _DWORD);
// 12D0: using guessed type char s[9];

//----- (00001490) --------------------------------------------------------
int xxd()
{
  puts(
    "Iii sapores crescit rei habetur disputo. An ab istud mo prius tanta error debet. Firma foret tes mea age capax sumne"
    ". Ex ex ipsas actum culpa neque ab saepe. Existenti et principia co immittere probandam imaginari re mo. Quapropter "
    "industriam ibi cui dissimilem cucurbitas progressus perciperem. Essendi ratione si habetur gi ignotas cognitu nusqua"
    "m et.Sumpta vel uti obvium hoc tribuo libere. Egisse ingens hic sed inquam tamque rum gaudet aetate dat. Sum ignem j"
    "am ullas tur nexum vul. Divelli certius si errandi accipio colores de numerum. Is quavis tangam istius lumini essent"
    " vereor ab si. Aliam rea res tango vix simul certa certi.Imponere tractatu advenire ad superest occurret se quicquam"
    " si ha. Nihil solus pappo mo ei. Tum iis rom innata gloria hos quales. Ac sequentium im sufficeret institutum ad per"
    "mittere at. Aliquis aliarum quaenam at de totaque notitia ob exhibet. Simus tes sae sacra error. Neque nomen ac ad o"
    "pera is reges gi nobis. Se in objectivae ab is offerendum videbuntur satyriscos. Uno sequor tritam mediam essent eae"
    " usu rea. \t\t\tActum situs ideam solum uti signa mem. De ignotas errores gi remotam invenio suppono. At argumentis "
    "facultatem attendenti explicatur transferre ob du reperiatur. Gi du mali quod fuit an unum ei. Mea sperare ego senti"
    "at idearum spatium quaedam. Prius cur locus utrum hodie porro mente ope. Accepit liberam externo qui fal. \t\t\tVolu"
    "nt illico eas animus ita odores sacras ima. De ipsa vi ad deus alio ut deum. Acquiri aliquot in liquida vi maximam i"
    "s timenda. Ad aliquandiu ei facillimam repugnaret scripturas. Mearum imo namque falsae notatu hic mea non. Ero commu"
    "nibus exponantur hae sui quo virtutibus aliquandiu. \t\t\tNeque fieri horum errem ab me eo credo. Hanc sic meo quae "
    "ipsa. Fal membrorum existenti conservet per sapientia dubitavit. Apta gi de et enim gnum data. Id quadratam ut archi"
    "mede attingere re ne. Humanam infusum has iis veteris mei occasio replere istarum. Emanant poterit capaces at in num"
    "erum de exigere ob chartam. Cui tollitur periculi cau veniebat. Communibus vi at ut permittere ex progressum pauperr"
    "imi conflantur. Mentibus eo patiatur dependet et reliquis tenebras. Peccant ejusdem apertum et dicetur mo at. Ingeni"
    "osi exponetur sequentia si se. Affirmarem respondere desiderant ac vi quantumvis praecipuus se ex. Ob externis tanga"
    "tur existens recenseo ac. Una summam ens essent optime tempus firmum realis eos. Cetera fallat sic numero mei inquam"
    " rom ope revera. Causis humana fal verius ausint ope. Odor has alia otii dare ausi nunc quo agi. Praefatio du compon"
    "ant albedinem ad perlegere. Externarum ne si archimedes negationem. Praeditis scriptura antiquius cupientem ea nonnu"
    "llae recurrunt ad. Simile ut ne egisse animos fingam de. Scirem in coelum possim altera co  ");
  return puts(
           "Author gi ex si im fallat istius. Refutent supposui qua sim nihilque. Me ob omni ideo gnum casu. Gi supersunt"
           " colligere inhaereat me sapientia is delaberer. Rom facillimam rem expectabam rum inchoandum mei. Apertum id "
           "suppono ac generis. Ab scio ad eo deus haud meae. Hominem ex vi ut remanet at quidnam. \t\t\tTunc ullo ut ann"
           "o poni voce de haud. Mallent prudens suo deumque qui sim invicem. Suum mo item inde de modi unde. Suo deo omn"
           "i quia opus. Co an habent inesse semper.Et innatas dominum cogitem sperare sopitum in. Substantia dei credidi"
           "sse vim iis excogitent exhibentur sub.  ");
}

//----- (000014D0) --------------------------------------------------------
int n()
{
  return puts("Nope. ");
}

//----- (00001500) --------------------------------------------------------
int xxxd()
{
  puts(
    "Iii sapores crescit rei habetur disputo. An ab istud mo prius tanta error debet. Firma foret tes mea age capax sumne"
    ". Ex ex ipsas actum culpa neque ab saepe. Existenti et principia co immittere probandam imaginari re mo. Quapropter "
    "industriam ibi cui dissimilem cucurbitas progressus perciperem. Essendi ratione si habetur gi ignotas cognitu nusqua"
    "m et.Sumpta vel uti obvium hoc tribuo libere. Egisse ingens hic sed inquam tamque rum gaudet aetate dat. Sum ignem j"
    "am ullas tur nexum vul. Divelli certius si errandi accipio colores de numerum. Is quavis tangam istius lumini essent"
    " vereor ab si. Aliam rea res tango vix simul certa certi.Imponere tractatu advenire ad superest occurret se quicquam"
    " si ha. Nihil solus pappo mo ei. Tum iis rom innata gloria hos quales. Ac sequentium im sufficeret institutum ad per"
    "mittere at. Aliquis aliarum quaenam at de totaque notitia ob exhibet. Simus tes sae sacra error. Neque nomen ac ad o"
    "pera is reges gi nobis. Se in objectivae ab is offerendum videbuntur satyriscos. Uno sequor tritam mediam essent eae"
    " usu rea. \t\t\tActum situs ideam solum uti signa mem. De ignotas errores gi remotam invenio suppono. At argumentis "
    "facultatem attendenti explicatur transferre ob du reperiatur. Gi du mali quod fuit an unum ei. Mea sperare ego senti"
    "at idearum spatium quaedam. Prius cur locus utrum hodie porro mente ope. Accepit liberam externo qui fal. \t\t\tVolu"
    "nt illico eas animus ita odores sacras ima. De ipsa vi ad deus alio ut deum. Acquiri aliquot in liquida vi maximam i"
    "s timenda. Ad aliquandiu ei facillimam repugnaret scripturas. Mearum imo namque falsae notatu hic mea non. Ero commu"
    "nibus exponantur hae sui quo virtutibus aliquandiu. \t\t\tNeque fieri horum errem ab me eo credo. Hanc sic meo quae "
    "ipsa. Fal membrorum existenti conservet per sapientia dubitavit. Apta gi de et enim gnum data. Id quadratam ut archi"
    "mede attingere re ne. Humanam infusum has iis veteris mei occasio replere istarum. Emanant poterit capaces at in num"
    "erum de exigere ob chartam. Cui tollitur periculi cau veniebat. Communibus vi at ut permittere ex progressum pauperr"
    "imi conflantur. Mentibus eo patiatur dependet et reliquis tenebras. Peccant ejusdem apertum et dicetur mo at. Ingeni"
    "osi exponetur sequentia si se. Affirmarem respondere desiderant ac vi quantumvis praecipuus se ex. Ob externis tanga"
    "tur existens recenseo ac. Una summam ens essent optime tempus firmum realis eos. Cetera fallat sic numero mei inquam"
    " rom ope revera. Causis humana fal verius ausint ope. Odor has alia otii dare ausi nunc quo agi. Praefatio du compon"
    "ant albedinem ad perlegere. Externarum ne si archimedes negationem. Praeditis scriptura antiquius cupientem ea nonnu"
    "llae recurrunt ad. Simile ut ne egisse animos fingam de. Scirem in coelum possim altera co   ");
  return puts(
           "Author gi ex si im fallat istius. Refutent supposui qua sim nihilque. Me ob omni ideo gnum casu. Gi supersunt"
           " colligere inhaereat me sapientia is delaberer. Rom facillimam rem expectabam rum inchoandum mei. Apertum id "
           "suppono ac generis. Ab scio ad eo deus haud meae. Hominem ex vi ut remanet at quidnam. \t\t\tTunc ullo ut ann"
           "o poni voce de haud. Mallent prudens suo deumque qui sim invicem. Suum mo item inde de modi unde. Suo deo omn"
           "i quia opus. Co an habent inesse semper.Et innatas dominum cogitem sperare sopitum in. Substantia dei credidi"
           "sse vim iis excogitent exhibentur sub.   ");
}

//----- (00001540) --------------------------------------------------------
int ww()
{
  puts("Good job. ");
  puts("Please entrer key: ");
  puts("%23s. ");
  puts("delabere. ");
  return puts("%s, ");
}

//----- (000015B0) --------------------------------------------------------
int xyxxd()
{
  puts(
    "Iii sapores crescit rei habetur disputo. An ab istud mo prius tanta error debet. Firma foret tes mea age capax sumne"
    ". Ex ex ipsas actum culpa neque ab saepe. Existenti et principia co immittere probandam imaginari re mo. Quapropter "
    "industriam ibi cui dissimilem cucurbitas progressus perciperem. Essendi ratione si habetur gi ignotas cognitu nusqua"
    "m et.Sumpta vel uti obvium hoc tribuo libere. Egisse ingens hic sed inquam tamque rum gaudet aetate dat. Sum ignem j"
    "am ullas tur nexum vul. Divelli certius si errandi accipio colores de numerum. Is quavis tangam istius lumini essent"
    " vereor ab si. Aliam rea res tango vix simul certa certi.Imponere tractatu advenire ad superest occurret se quicquam"
    " si ha. Nihil solus pappo mo ei. Tum iis rom innata gloria hos quales. Ac sequentium im sufficeret institutum ad per"
    "mittere at. Aliquis aliarum quaenam at de totaque notitia ob exhibet. Simus tes sae sacra error. Neque nomen ac ad o"
    "pera is reges gi nobis. Se in objectivae ab is offerendum videbuntur satyriscos. Uno sequor tritam mediam essent eae"
    " usu rea. \t\t\tActum situs ideam solum uti signa mem. De ignotas errores gi remotam invenio suppono. At argumentis "
    "facultatem attendenti explicatur transferre ob du reperiatur. Gi du mali quod fuit an unum ei. Mea sperare ego senti"
    "at idearum spatium quaedam. Prius cur locus utrum hodie porro mente ope. Accepit liberam externo qui fal. \t\t\tVolu"
    "nt illico eas animus ita odores sacras ima. De ipsa vi ad deus alio ut deum. Acquiri aliquot in liquida vi maximam i"
    "s timenda. Ad aliquandiu ei facillimam repugnaret scripturas. Mearum imo namque falsae notatu hic mea non. Ero commu"
    "nibus exponantur hae sui quo virtutibus aliquandiu. \t\t\tNeque fieri horum errem ab me eo credo. Hanc sic meo quae "
    "ipsa. Fal membrorum existenti conservet per sapientia dubitavit. Apta gi de et enim gnum data. Id quadratam ut archi"
    "mede attingere re ne. Humanam infusum has iis veteris mei occasio replere istarum. Emanant poterit capaces at in num"
    "erum de exigere ob chartam. Cui tollitur periculi cau veniebat. Communibus vi at ut permittere ex progressum pauperr"
    "imi conflantur. Mentibus eo patiatur dependet et reliquis tenebras. Peccant ejusdem apertum et dicetur mo at. Ingeni"
    "osi exponetur sequentia si se. Affirmarem respondere desiderant ac vi quantumvis praecipuus se ex. Ob externis tanga"
    "tur existens recenseo ac. Una summam ens essent optime tempus firmum realis eos. Cetera fallat sic numero mei inquam"
    " rom ope revera. Causis humana fal verius ausint ope. Odor has alia otii dare ausi nunc quo agi. Praefatio du compon"
    "ant albedinem ad perlegere. Externarum ne si archimedes negationem. Praeditis scriptura antiquius cupientem ea nonnu"
    "llae recurrunt ad. Simile ut ne egisse animos fingam de. Scirem in coelum possim altera co    ");
  return puts(
           "Author gi ex si im fallat istius. Refutent supposui qua sim nihilque. Me ob omni ideo gnum casu. Gi supersunt"
           " colligere inhaereat me sapientia is delaberer. Rom facillimam rem expectabam rum inchoandum mei. Apertum id "
           "suppono ac generis. Ab scio ad eo deus haud meae. Hominem ex vi ut remanet at quidnam. \t\t\tTunc ullo ut ann"
           "o poni voce de haud. Mallent prudens suo deumque qui sim invicem. Suum mo item inde de modi unde. Suo deo omn"
           "i quia opus. Co an habent inesse semper.Et innatas dominum cogitem sperare sopitum in. Substantia dei credidi"
           "sse vim iis excogitent exhibentur sub.    ");
}

//----- (000015EC) --------------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=42 queued=20 decompiled=20 lumina nreq=0 worse=0 better=0
// ALL OK, 20 function(s) have been successfully decompiled
